PaperからSpigotへ
GiganticMinecraft/Petra pull request #21
Opened 2022-01-18 04:05 UTC by Lucky3028

close #13

2022-01-18 04:06 UTC, Lucky3028 commented
PlayerPreRespawnEventやBlockDestroyEventのあたりが、これできちんと動くかどうか怪しい

2022-01-18 04:53 UTC, Lucky3028 reviewed
コミットメッセージの誤字：Pre -> Post

2022-01-18 04:54 UTC, Lucky3028 commented
ということは置き換えできてないじゃん！Preと勘違いしてた！

2022-01-18 05:23 UTC, Lucky3028 commented
LOWESTからHIGHESTに向かって実行されるらしいのでたぶん大丈夫

2023-01-12 09:18 UTC, m2en requested changes
あまり中身についてはレビューできなかったのであとは @KisaragiEffective に投げます

2023-01-12 09:18 UTC, m1sk9 commented on README.md
>  その他は各自が必要だと判断した場合のみ記載してください。
JavaDocs ではなく JavaDoc だと思います

Kotlin でのドキュメンテーションコメントは基本的に KDoc だと思うんですが、JavaDoc でもいいのかな ...

https://kotlinlang.org/docs/kotlin-doc.html

2023-01-13 10:36 UTC, m2en approved these changes
LGTM

2023-01-13 10:36 UTC, merged